name: scango
description: "Scan & Go Smart Shopping Cart Flutter App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  google_fonts: ^8.2.1
  flutter_svg: ^2.3.0
  image_picker: ^1.2.3
  http: ^1.6.0
  local_auth: ^3.0.2
  camera: ^0.12.0+2
  flutter_secure_storage: ^11.0.0
  socket_io_client: ^3.1.6
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/scango_logo.png
